# general
live_config_reload = true

[font]
size = 11

[window]
# padding
padding = { x = 8, y = 8 }
opacity = 0.94

[colors]
cursor = { cursor = "#BD93F9" }

[colors.primary]
background = '#272537'
foreground = '#e8d4f2'

[colors.normal]
black   = '#44475A'
red     = '#FF5555'
green   = '#50FA7B'
yellow  = '#F1FA8C'
blue    = '#6272A4'
magenta = '#FF79C6'
cyan    = '#8BE9FD'
white   = '#e8e6e9'

[colors.bright]
black   = '#626681'
red     = '#ff8b8b'
green   = '#8affa5'
yellow  = '#fbffae'
blue    = '#8198ce'
magenta = '#ffa2de'
cyan    = '#a0f2ff'
white   = '#F8F8F2'

[cursor]
style = { shape = "Beam", blinking = "On" }
unfocused_hollow = false
thickness = 0.2
